const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const events=[],nodes=[],buffers=[],c={window:null,console,atob,Uint8Array};c.window=c;vm.createContext(c);for(const f of ['songs','motion','pedal','audio-manifest','audio'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);
const manifest=c.PIANO_AUDIO_MANIFEST;let clock=0;function param(value=0){return{value,events:[],setValueAtTime(v,t){this.events.push({kind:'set',v,t});},linearRampToValueAtTime(v,t){this.events.push({kind:'linear',v,t});},exponentialRampToValueAtTime(v,t){assert(v>0);this.events.push({kind:'exponential',v,t});},cancelScheduledValues(t){this.events=this.events.filter(e=>e.t<t);},setTargetAtTime(v,t){this.events.push({kind:'target',v,t});}};}
function node(type){let n={id:nodes.length,type,connections:[],gain:param(1),playbackRate:param(1),frequency:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),connect(other){this.connections.push(other.id);},disconnect(){},start(t){events.push({kind:'start',node:this,t});},stop(t){events.push({kind:'stop',node:this,t});}};nodes.push(n);return n;}
const ctx={sampleRate:44100,destination:node('destination'),get currentTime(){return clock;},createGain:()=>node('gain'),createDynamicsCompressor:()=>node('compressor'),createConvolver:()=>node('convolver'),createBiquadFilter:()=>node('filter'),createBufferSource:()=>node('source'),createBuffer(ch,length,sr){let a=Array.from({length:ch},()=>new Float32Array(length)),b={length,sampleRate:sr,numberOfChannels:ch,duration:length/sr,getChannelData:i=>a[i],channels:a};buffers.push(b);return b;},async decodeAudioData(bytes){let id=Buffer.from(bytes).toString(),a=manifest.assets[id];assert(a);return{id,duration:a.duration,length:Math.round(a.duration*44100),sampleRate:44100,numberOfChannels:2};}};
c.PIANO_AUDIO_DATA=Object.fromEntries(Object.keys(manifest.assets).map(id=>[id,Buffer.from(id).toString('base64')]));
async function run(){
 let hashes=JSON.parse(fs.readFileSync('v6-note-hashes.json'));for(const s of c.SONGS)assert.equal(crypto.createHash('sha256').update(JSON.stringify(s.notes)).digest('hex'),hashes[s.id]);
 let mapping=0,maxShift=0;for(let pitch=21;pitch<=108;pitch++)for(let velocity=1;velocity<=127;velocity++){let plan=c.PianoAudio.notePlan([0,.5,pitch,velocity,0]);assert(plan.length>=1&&plan.length<=2);assert(Math.abs(plan.reduce((s,p)=>s+p.weight*p.weight,0)-1)<1e-9);for(const p of plan){assert(manifest.assets[p.id]);let shift=Math.abs(p.root-pitch);maxShift=Math.max(maxShift,shift);assert(shift<=2);assert(Math.abs(p.root+12*Math.log2(p.rate)-pitch)<1e-9);}mapping++;}
 let levels=c.PianoAudio.layerMix(32),other=c.PianoAudio.layerMix(116);assert.notEqual(levels[0].layer.id,other[0].layer.id);for(const boundary of [32,66,92,116]){const a=c.PianoAudio.layerMix(boundary-.001),b=c.PianoAudio.layerMix(boundary+.001),weights=p=>Object.fromEntries(p.map(x=>[x.layer.id,x.weight]));let A=weights(a),B=weights(b);for(const k of new Set([...Object.keys(A),...Object.keys(B)]))assert(Math.abs((A[k]||0)-(B[k]||0))<.001,'Audible layer step');}
 const n=[0,.5,60,90,0],dry={notes:[n],pedals:[],duration:8},held={...dry,pedals:[[0,127],[2,0]]},caught={...dry,pedals:[[.6,127],[2,0]]},level=(s,t)=>c.PianoPedal.levelAt(c.PianoAudio.dampingEnvelope(s,n,1,7),t);assert.equal(level(dry,.4),1,'Natural decay applied twice');assert(level(dry,1)<.0001);assert.equal(level(held,1.5),1);assert(level(held,2.2)<.02);assert(level(caught,1)<1&&level(caught,1)>.01,'Re-pedal lost tail or restored energy');assert.equal(c.PianoPedal.levelAt(c.PianoAudio.dampingEnvelope(dry,[0,.1,96,90,0],1,3),1),1,'Damper added to treble');
 const engine=c.PianoAudio.create(ctx),song=c.SONGS[0];let progress=[];await engine.loadForSong(song,p=>progress.push(p));assert.equal(progress.at(-1).loaded,progress.at(-1).total);engine.startTransport(song,0,.1);for(const note of song.notes.filter(n=>n[0]<20))engine.startNote(song,note,.1+note[0],1);assert.equal(engine.stats.attacks.length,song.notes.filter(n=>n[0]<20).length);let gainSources=events.filter(e=>e.kind==='start'&&e.node.buffer?.id);assert(gainSources.some(e=>e.node.buffer.id.startsWith('pedalD')));assert(gainSources.some(e=>e.node.buffer.id.startsWith('rel')));const compressor=nodes.find(n=>n.type==='compressor');assert.equal(compressor.threshold.value,-2.5);assert.equal(engine.latency,.006);assert(buffers.every(b=>b.channels.every(a=>a.every(Number.isFinite))));
 const fixture={sampleRate:ctx.sampleRate,notes:song.notes.filter(n=>n[0]<20),nodes:nodes.map(n=>({id:n.id,type:n.type,connections:n.connections,gain:n.gain,frequency:n.frequency,threshold:n.threshold,knee:n.knee,ratio:n.ratio,attack:n.attack,release:n.release,buffer:n.buffer?.id?{id:n.buffer.id}:n.buffer?.channels?{sampleRate:n.buffer.sampleRate,channels:n.buffer.channels.map(a=>Array.from(a))}:null,playbackRate:n.playbackRate})),events:events.map(e=>({kind:e.kind,id:e.node.id,t:e.t})),latency:engine.latency};fs.writeFileSync('audio-render-fixture.json',JSON.stringify(fixture));
 let before=events.length;engine.stopAll();assert.equal(engine.voices.size,0);assert(events.slice(before).some(e=>e.kind==='stop'));let allSongNotes=0,preloadedSongs=[];
 for(const s of c.SONGS){await engine.loadForSong(s);let ids=new Set();for(const n of s.notes){for(const plan of c.PianoAudio.notePlan(n)){assert(engine.buffers.has(plan.id),'Selected song sample missing');ids.add(plan.id);}allSongNotes++;}for(const list of Object.values(manifest.mechanical))for(const id of list)ids.add(id);assert.equal(engine.buffers.size,ids.size,'Previous song sample cache retained');preloadedSongs.push({id:s.id,samples:ids.size,notes:s.notes.length});}
 await engine.loadForSong(song);const repeated={notes:[],pedals:[[0,127]],duration:10};let repetitions=[0,.1,.2].map(t=>[t,.02,60,90,0]);repeated.notes=repetitions;let first=engine.startNote(repeated,repetitions[0],30);engine.startNote(repeated,repetitions[1],30.1);engine.startNote(repeated,repetitions[2],30.2);assert(Math.abs(first.stopAt-30.245)<1e-8,'Repeated strikes accumulate unlimited tails');engine.stopAll();
 console.log(JSON.stringify({preloadedSongs,allSongNotes,songCacheEviction:true,repeatedStrikeTailLimit:true,mappingSamples:mapping,maxTranspositionSemitones:maxShift,recordedLayers:4,layerCrossfadesContinuous:true,naturalSampleDecay:true,pedalHoldAndRelease:true,repedalCannotRestoreEnergy:true,undampedTreble:true,loadedSamples:engine.stats.loadedSamples,scheduledNotes:fixture.notes.length,recordedKeyAndPedalNoise:true,moderateReverb:true,limiterLatency:engine.latency,stopCancelsVoices:true,notesAndFingeringPreserved:true}));
}
run().catch(e=>{console.error(e);process.exitCode=1;});
