const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;vm.runInThisContext(fs.readFileSync('dist/songs.js','utf8'));vm.runInThisContext(fs.readFileSync('dist/score.js','utf8'));
const song=(notes,n=4,d=4)=>({notes,scoreMetadata:{tempos:[{time:0,beat:0,bpm:60}],timeSignatures:[{beat:0,numerator:n,denominator:d}],keySignatures:[]}}),notes=(times,dur=.4)=>times.map((t,i)=>[t,dur,64+i%4,80,0,1]);
let simple=PianoScore.model(song(notes([0,.5,1,1.5,2,2.5,3,3.5])));assert.equal(simple.beams.length,4);assert(simple.beams.every(b=>b.clusters.length===2));
let compound=PianoScore.model(song(notes([0,.5,1,1.5,2,2.5]),6,8));assert.equal(compound.beams.length,2);assert(compound.beams.every(b=>b.clusters.length===3));
assert.equal(PianoScore.model(song(notes([0,.75]))).beams.length,0,'Rest must break beam');assert.equal(PianoScore.model(song(notes([0,1],.95))).beams.length,0,'Quarters cannot be beamed');
let chord=song([...notes([0,.5]),[0,.4,72,80,0,3],[.5,.4,74,80,0,4]].sort((a,b)=>a[0]-b[0]));let m=PianoScore.model(chord);assert.equal(m.beams.length,1);assert.equal(m.beams[0].clusters.length,2);assert.equal(m.beams[0].clusters[0].notes.length,2);
let mixed=PianoScore.model(song([[0,.22,64,80,0,1],[.25,.22,65,80,0,2],[.5,.44,67,80,0,3]]));assert.equal(mixed.beams.length,1);assert.deepEqual(mixed.beams[0].clusters.map(c=>c.flags),[2,2,1]);
let groups=0;for(const s of SONGS){for(const b of PianoScore.model(s).beams){assert(b.clusters.length>1);assert(b.clusters.every(c=>c.flags>0));assert(b.clusters.every(c=>c.lane===b.clusters[0].lane));assert(b.clusters.every(c=>c.cell===b.clusters[0].cell));groups++}}
console.log(JSON.stringify({beamGroups:groups,simpleMeter:true,compoundMeter:true,restsBreakBeams:true,quarterNotesUnbeamed:true,chordStems:true,mixedSecondaryBeams:true}));
