const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map(),songButtons=[],cameraButtons=['auto','hands','portrait','pedal','wide','orbit'].map(mode=>element('',{camera:mode}));
function element(id='',dataset={}){let set=new Set(),children=new Map();return{id,dataset,style:{},value:({'volume':'.7','speed':'1','seek':'0'})[id]||'',disabled:false,clientWidth:1300,clientHeight:640,classList:{add:x=>set.add(x),remove:x=>set.delete(x),toggle:(x,b)=>b?set.add(x):set.delete(x)},getContext:()=>new Proxy({},{get:(o,k)=>()=>{}}),setAttribute(){},addEventListener(){},append:b=>songButtons.push(b),querySelector:s=>{if(!children.has(s))children.set(s,element());return children.get(s)},setPointerCapture(){},textContent:'',innerHTML:''}}
let frame,clock=0,scheduled=[],draws=0,scheduler,tips=[],footDraw,pedalDraw;function record(...args){for(const v of args.flat(3))if(typeof v==='number')assert(Number.isFinite(v),'Nonfinite model');if(Array.isArray(args[1])&&args[1][0]===.014&&args[1][1]===.013&&args[1][2]===.019)tips.push(args[0]);if(Array.isArray(args[1])&&args[1][0]===.060&&args[1][1]===.040&&args[1][2]===.145)footDraw=args;if(Array.isArray(args[1])&&args[1][0]===.045&&args[1][1]===.024&&args[1][2]===.20&&args[0][0]===.12)pedalDraw=args;draws++}
const document={title:'',activeElement:{tagName:'BODY'},getElementById:id=>{if(!elements.has(id))elements.set(id,element(id));return elements.get(id)},createElement:()=>element(),querySelectorAll:s=>s==='.song'?songButtons:cameraButtons,querySelector:()=>element(),addEventListener(){},modelContext:{registerTool:tool=>{globalThis.registered=tool}}};
function node(){return{gain:{value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}},frequency:{value:0},threshold:{value:0},ratio:{value:0},knee:{value:0},attack:{value:0},release:{value:0},connect(){},disconnect(){},setPeriodicWave(){},start(t){scheduled.push({time:t,freq:this.frequency.value})},stop(){}}}
let sampleMeta,decodeGate;
class AudioContext{get currentTime(){return clock}getOutputTimestamp(){return{contextTime:clock,performanceTime:1000}}resume(){return Promise.resolve()}createGain(){return node()}createBiquadFilter(){return{...node(),Q:{value:0}}}createBufferSource(){return{...node(),playbackRate:{value:1}}}async decodeAudioData(bytes){if(decodeGate)await decodeGate();let id=Buffer.from(bytes).toString();return Promise.resolve({...sampleMeta.assets[id],id,length:Math.ceil(sampleMeta.assets[id].duration*44100)});}createDynamicsCompressor(){return node()}createConvolver(){return node()}createOscillator(){return node()}createPeriodicWave(){return{}}createBuffer(n,l){return{getChannelData:()=>new Float32Array(l)}}sampleRate=8000;destination={}}
let context={document,window:null,performance:{now:()=>1000},AudioContext,console,devicePixelRatio:1,innerWidth:1440,matchMedia:()=>({matches:false}),setInterval:f=>{scheduler=f;return 1},clearInterval(){},AbortController,atob,Uint8Array,requestAnimationFrame:f=>frame=f,RecitalGL:{create:()=>({begin:record,box:record,ball:record,bone:record,piece:(shape,p,s,c,rx)=>record(p,s,c,0,rx),segment:record})},addEventListener(){}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('dist/songs.js','utf8'),context);vm.runInContext(fs.readFileSync('dist/motion.js','utf8'),context);vm.runInContext(fs.readFileSync('dist/pedal.js','utf8'),context);vm.runInContext(fs.readFileSync('dist/score.js','utf8'),context);vm.runInContext(fs.readFileSync('dist/audio-manifest.js','utf8'),context);sampleMeta=context.PIANO_AUDIO_MANIFEST;context.PIANO_AUDIO_DATA=Object.fromEntries(Object.keys(sampleMeta.assets).map(id=>[id,Buffer.from(id).toString('base64')]));vm.runInContext(fs.readFileSync('dist/audio.js','utf8'),context);vm.runInContext(fs.readFileSync('dist/app.js','utf8'),context);
async function run(){
let scoreSamples=0;for(const s of context.SONGS){for(const n of s.notes.filter((_,i)=>i%40===0)){const b=context.PianoScore.beatAt(s,n[0]);assert(Math.abs(context.PianoScore.timeAt(s,b)-n[0])<1e-8);scoreSamples++}}assert.equal(songButtons.length,18);frame(1000);assert(draws>300);let samples=0;
for(let song of context.SONGS){context.recital.choose(song.id);assert.equal(context.recital.getState().song,song.id);for(let t of [0,1,15,32,60,song.duration-3]){context.recital.seek(t);frame(1016);let expected=[...new Set(song.notes.filter(n=>n[0]<=t&&n[0]+n[1]>t).map(n=>n[2]))].sort((a,b)=>a-b);assert.equal(context.recitalScoreDebug.time,t);let scoreExpected=song.notes.filter(n=>n[0]<=t&&n[0]+n[1]>t);if(scoreExpected.every(n=>n[0]>t-2&&context.PianoScore.beatAt(song,n[0])>context.recitalScoreDebug.beat-3))assert.deepEqual([...new Set(context.recitalScoreDebug.activeNotes)].sort((a,b)=>a-b),expected);let actual=Array.from(context.recitalDebug.activeNotes).sort((a,b)=>a-b);assert.deepEqual(actual,expected,'Key synchronization: '+song.id+' @ '+t);samples++;}}
let fingerSamples=0,maxContactError=0,maxArmError=0;
for(const song of context.SONGS){context.recital.choose(song.id);assert.equal(song.notes.length,song.sourceNoteCount);for(let i=0;i<song.notes.length;i+=40){let n=song.notes[i];context.recital.seek(n[0]+.0001);frame(1016);let debug=context.recitalDebug;
 for(const h of debug.hands)for(const f of h.fingers){for(let j=0;j<3;j++){let length=Math.hypot(...f.points[j+1].map((v,k)=>v-f.points[j][k]));assert(Math.abs(length-f.lengths[j])<1e-8,'Finger segment stretched');}assert(f.angles[1]>=0&&f.angles[1]<=1.82001);assert(f.angles[2]>=0&&f.angles[2]<=1.1831);if(f.contact)maxContactError=Math.max(maxContactError,f.error)}
 for(const arm of debug.arms){for(const [a,b,length] of [[arm.shoulder,arm.elbow,arm.lengths[0]],[arm.elbow,arm.wrist,arm.lengths[1]]])assert(Math.abs(Math.hypot(...a.map((v,k)=>v-b[k]))-length)<1e-8,'Arm segment stretched');maxArmError=Math.max(maxArmError,arm.error)}
 fingerSamples++;
 }}
const K=context.PianoMotion.keyboard;assert(Math.abs(K.blackLength/K.whiteLength-95/148)<1e-9);assert(Math.abs(K.blackWidth/K.pitch-14/23.5)<1e-9);
// Continuous lift and replacement: sample a release through the next attack.
let continuous=0,maxStep=0;for(const song of context.SONGS){for(let h=0;h<2;h++){let seq=song.motion.hands[h].fingers.find(a=>a.length>5);if(!seq)continue;let next=seq[3],start=Math.max(0,next.t-.2),last=null;for(let t=start;t<=next.t+.03;t+=1/240){let p=context.PianoMotion.pose(song,t).hands[h];for(const f of p.fingers)if(last){let d=Math.hypot(...f.points[3].map((v,k)=>v-last[f.f][k]));maxStep=Math.max(maxStep,d)}last=p.fingers.map(f=>f.points[3]);continuous++}}}
assert(maxContactError<.007,'Contact error '+maxContactError);assert(maxArmError<.015,'Arm cannot reach '+maxArmError);
let pedalRenderSamples=0;
for(const song of context.SONGS){context.recital.choose(song.id);for(const value of [0,127]){let event=song.pedals.find(e=>e[1]===value);if(!event)continue;context.recital.seek(event[0]);frame(1016);assert.equal(context.recitalDebug.pedalDown,value>=64);assert(Math.abs(context.recitalDebug.pedalPosition-value/127)<1e-8);let center=footDraw[0],angle=footDraw[4];assert(Math.abs(center[1]+Math.sin(angle)*.145-.06)<1e-8,'Heel lifted');assert(Math.abs(center[2]-Math.cos(angle)*.145+.65)<1e-8,'Heel slid');if(value===127)assert(pedalDraw[4]<0,'Pedal did not depress');else assert(Math.abs(pedalDraw[4])<1e-8);pedalRenderSamples++;}}
cameraButtons.find(b=>b.dataset.camera==='pedal').onclick();frame(1016);assert.equal(context.recitalDebug.camera,'pedal');
context.recital.choose('hero');context.recital.seek(0);await context.recital.play();assert(context.recital.getState().playing);for(clock=0;clock<20;clock+=.025)scheduler();let expected=context.SONGS[0].notes.filter(n=>n[0]+.08<clock+.18);let attacks=context.recitalAudioDebug.attacks;assert.equal(attacks.length,expected.length);for(let i=0;i<attacks.length;i++){assert(Math.abs(attacks[i].when-(expected[i][0]+.08))<.011,'Audio onset');assert.equal(attacks[i].pitch,expected[i][2]);for(const src of attacks[i].sources)assert(Math.abs(src.root+12*Math.log2(src.rate)-expected[i][2])<1e-9,'Sample transposition');}
const verifiedAttacks=attacks.length;clock=1;frame(1032);assert(Math.abs(context.recital.getState().time-.914)<1e-9);context.recital.pause();let paused=context.recital.getState().time;clock=2;frame(1048);assert.equal(context.recital.getState().time,paused);context.recital.choose('moon');context.recital.seek(13);frame(1064);assert(context.recitalDebug.activeNotes.length>0);
let rejected=false;try{context.recital.choose('invalid')}catch{rejected=true}assert(rejected);assert.equal(context.recital.getState().song,'moon');assert(globalThis.registered);let result=globalThis.registered.execute({songId:'clair'});assert.equal(result.song,'clair');assert.throws(()=>globalThis.registered.execute({songId:'bad'}));assert.equal(context.recital.getState().song,'clair');
// Delayed decoding: selecting and seeking during a load cannot start an obsolete song.
let gates=[];decodeGate=()=>new Promise(resolve=>gates.push(resolve));context.recital.choose('elise');let obsolete=context.recital.play();await new Promise(setImmediate);assert(context.recital.getState().loading);assert(!context.recital.getState().playing);context.recital.choose('revolution');context.recital.seek(9);context.recital.pause();decodeGate=null;for(const resolve of gates)resolve();await obsolete;await new Promise(setImmediate);assert.equal(context.recital.getState().song,'revolution');assert.equal(context.recital.getState().time,9);assert(!context.recital.getState().playing&&!context.recital.getState().loading);assert(!elements.get('play').disabled);await context.recital.play();assert(context.recital.getState().playing);elements.get('speed').onchange({target:{value:'.75'}});await new Promise(setImmediate);assert.equal(context.recital.getState().speed,.75);assert(context.recital.getState().playing);context.recital.pause();
console.log(JSON.stringify({loadingCancellation:true,speedChangeWithSamples:true,songs:18,scoreTempoRoundTripSamples:scoreSamples,keyboardSyncSamples:samples,fixedSkeletonSamples:fingerSamples,maxContactError,maxArmError,continuousFrames:continuous,maxTipStepAt240Hz:maxStep,keyboardRatios:true,pedalRenderSamples,fixedHeel:true,pedalCamera:true,audioPitchAndOnsetSamples:verifiedAttacks,sampledGrand:true,limiterLatencyCompensated:true,pause:true,selection:true,finiteSceneTransforms:true,webmcpStateAndValidation:true,renderCalls:draws}));
}
run().catch(e=>{console.error(e);process.exitCode=1});
